### ISSUE TITLE
Investigación de funcionamiento SqLite y Flask

### ISSUE THREAD

**Issue by Thorney1** [Thorney1/Proyecto-Ing.Software#1]
Postear aquí cualquier avance o información requerida para el desarrollo

**Comment by Thorney1** [comment]
Zip con sqlite

[sqlite-dll-win64-x64-3390400.zip](https://github.com/Thorney1/Proyecto-Ing.Software/files/9729038/sqlite-dll-win64-x64-3390400.zip)

**Comment by Chocmanblack** [comment]
Método de instalación de SqLite como también SqLite Studio 2022 👍 

https://www.youtube.com/watch?v=elhEOwXZTSw

**Comment by Thorney1** [comment]
Pequeña prueba de creación de tablas(transcripción de código creado por SQLite, debido a que GitHub no soporta archivo .db en comentarios). bastante intuitivo

> CREATE TABLE Cliente (
    Nombre    CHAR,
    Apellido  CHAR,
    Direccion,
    PRIMARY KEY (
        Nombre
    )
);
